### ISSUE TITLE
Completely don't know how to use

### ISSUE THREAD

**Issue by Matsuri247** [boschresearch/ISSA#2]
how to train and inference？Nearly no instructions？
And how to prepare the pretrained model of GAN generator（the .pkl file）？

**Comment by YumengLi007** [comment]
Hi @Matsuri247 , sorry for the unclearness. I have updated the README file, please check the instruction for [training](https://github.com/boschresearch/ISSA#training) and [inference](https://github.com/boschresearch/ISSA#inference). This issue #1 might be relevant as well.

**Comment by Matsuri247** [comment]
So accroding to issue https://github.com/boschresearch/ISSA/issues/1, firstly i need to train styleGAN3 on my own dataset to get the generated data and styleGAN model. Is it right？

**Comment by YumengLi007** [comment]
Yes, that's correct.

**Comment by Matsuri247** [comment]
According to your paper, this method maps the input image（E.g. real image from my own dataset）to latent code w plus. Then StyleGAN generator process the latent code and output the reconstructed image.  But I still don't understand the usage of fake image（i.e. why i need to prepare data_fake？）

**Comment by YumengLi007** [comment]
Hi, as mentioned in the paper, we use GAN generator to generate some fake images with ground-truth w (since you can sample random z and map it to w which can be stored together with the final image), to make the training converge faster. This is only for training the encoder. 
For inference, the encoder will just take the input image and output noise and style w, and pass them to the generator.

For instance, you could simply modify [gen_images.py](https://github.com/NVlabs/stylegan3/blob/main/gen_images.py) by having 
```
...
z = torch.from_numpy(np.random.RandomState(seed).randn(1, G.z_dim)).to(device)
w_samples = G.mapping(z, None,truncation_psi=1.0) 
imgs = G.synthesis(w_samples)
...
PIL.Image.fromarray(img[0], 'RGB').save(os.path.join(output_dir, fname))
np.savez(os.path.join(output_dir, 'npz_name.npz'), w=w_samples[0,0,:].cpu().numpy(), z=z[0,:].cpu().numpy())
```
to store both ground-truth w and fake images. 

![reg_w_loss](https://github.com/boschresearch/ISSA/assets/109459218/eb4ac8ca-2406-4d74-818a-6a9ca6c252b5)

**Comment by Matsuri247** [comment]
Maybe i've finally figured out the working pipeline：data_fake contains both fake images generated by StyleGAN and latent code w (which is mentioned in StyleGAN paper).  It is part of training process of ISSA. Is that correct？
By the way, why not provide some sample data mentioned in the configure file (i.e. data, data_fake, pkl_dir) ？it will be much more clear for people who do not familiar with GAN inversion to understand how to use this repo. Thank you for your patience.

**Comment by YumengLi007** [comment]
Yes,  you understand it correctly. It is part of the training process :)

You are right. In fact, I would very much love to, but simply due to license issues. This half-working repo is a compromised solution I could provide, unfortunately...

**Comment by Matsuri247** [comment]
i have another question about training. how long have you spent in training styleGAN3 and the proposed encoder in total？And what about the image resolution？

**Comment by YumengLi007** [comment]
I firstly tried on 128x256 resolution, it takes around 4 days to train the generator using 2V100 and another 3-4 days to train the encoder. 256x512 resolution probably would take 5-7 days for each part. 

This is just a rough estimation though. Nevertheless, you could see good reconstruction results in short time for the encoder training. Training longer would further improve the quality.
