### ISSUE TITLE
NameError: name 'random_masking' is not defined

### ISSUE THREAD

**Issue by MISSEY** [boschresearch/ISSA#4]
From where to import random_masking ?

https://github.com/boschresearch/ISSA/blob/main/training/masking.py#L44

**Comment by YumengLi007** [comment]
Hi @MISSEY ,
thanks for reporting this. Now it's fixed, please check [here](https://github.com/boschresearch/ISSA/blob/c33528f5dbf057d9b9a422cfe84ea288f1a5ae8b/training/masking.py#L33).

**Comment by MISSEY** [comment]
At line https://github.com/boschresearch/ISSA/blob/main/training/loss.py#L264
imgs have shape =  torch.Size([1, 3, 256, 512])

and I am getting result output size of 
fake_img = torch.Size([1, 3, 512, 512]), latent_w =torch.Size([1, 16, 512]) , input_noise = torch.Size([1, 512]), layer_noise = torch.Size([1, 256, 64, 128]) x 2  , all_masks = torch.Size([1, 1, 256, 512])

After 
```python
fake_g_pred = self.prep_d_output(fake_g_pred, use_feat=True)
real_g_pred = self.prep_d_output(real_g_pred, use_feat=False)
```
The shapes of fake_g_pred and real_g_pred are 

![image](https://github.com/boschresearch/ISSA/assets/11891755/abd0dee8-cf3b-4c6b-8564-79a180800b20)

![image](https://github.com/boschresearch/ISSA/assets/11891755/b0c431f9-4082-4046-82b5-93edc1bd46c1)


Shapes  of each tensor in list is inconsistent in fake_g_pred and real_g_pred, which lead to 

```bash
RuntimeError: The size of tensor a (257) must match the size of tensor b (129) at non-singleton dimension 2
```

at line https://github.com/boschresearch/ISSA/blob/main/training/loss.py#L283

**Comment by MISSEY** [comment]
I am not using gan generated fake images, use_w is false in config.

**Comment by YumengLi007** [comment]
What are the shapes of fake_g_pred, real_g_pred after these two lines and shapes of fake_img, real_img?
https://github.com/boschresearch/ISSA/blob/c33528f5dbf057d9b9a422cfe84ea288f1a5ae8b/training/loss.py#L268-L269

**Comment by MISSEY** [comment]
### fake_g_pred 
list:3

![image](https://github.com/boschresearch/ISSA/assets/11891755/deb368cb-7b71-422e-b3ff-88d50a4e8946)

### real_g_pred 
list:3

![image](https://github.com/boschresearch/ISSA/assets/11891755/c414e920-198f-499a-9363-9e01aa26ea1c)


### fake_img

torch.Size([1, 3, 512, 512])

### real_img 

torch.Size([1, 3, 256, 512])

**Comment by YumengLi007** [comment]
yes, that's the problem. Fake and real images should have the same size. For non-square images, you need to add aspect ratio argument in the generator

**Comment by MISSEY** [comment]
Then I have to train the generator again?

**Comment by MISSEY** [comment]
But I am using the images of size 1024x1024x3

**Comment by YumengLi007** [comment]
if your images are 1024x1024x3, then real_img should have size 512x512x3.
You should change the img_ratio to 1 in the config file here
https://github.com/boschresearch/ISSA/blob/c33528f5dbf057d9b9a422cfe84ea288f1a5ae8b/configs/mne_training.yml#L27

**Comment by MISSEY** [comment]
Worked !! 

Thank you
