### ISSUE TITLE
Request to upload modified "networks_stylegan2.py" code 

### ISSUE THREAD

**Issue by SelfishGene** [boschresearch/ISSA#6]
There is a long list of complicated instruction of how to copy and edit code from other repositories before being able to use this one.
For the sake of self containment, is it possible to upload your edits of all necessary files to serve as a single working example?

I believe I'm speaking of behalf of all potential users when I say that although we all appreciate the long list of detailed instructions in how-to.pdf, for 99.9% of potential users it will be much simpler to just upload your own edits of the original stylegan2 code and have all the necessary code in this single repository to use the basic functionality demonstrated in your paper. 
This way, the 99.9% of users will use your code, and the remaining 0.1% of users will use the instructions for their own custom needs.

**Comment by YumengLi007** [comment]
Hi @SelfishGene, 

first of all, thanks for your interest in our work! 

Secondly, I understand the circumstance and all the troubles caused for people who are interested in the work. But very unfortunately, this is the best I can offer considering the license constraints. I hope for your understanding!
Nevertheless, if there is anything unclear, please feel free to reach out, I will try to reply in a timely manner. 

Thank you!
