### ISSUE TITLE
Where's 'load_network_pkl' in torch_utils misc.py ?

### ISSUE THREAD

**Issue by LongVu219** [boschresearch/ISSA#7]
This function is used in [this line](https://github.com/boschresearch/ISSA/blob/03da56acb775bea612014b97c156550c30af23ca/train_encoder.py#L211)
I have searched for this function in many StyleGan version but i still can's find it, can you provide me this function please ? Some minor issues is that somehow your code is mis-included some library ex, in network_stylegan2.py in how-to.pdf you have instructed to use custom_layers.EqualConvTranspose2d and custom_layers.PixelNorm in SynthesisBlock but custom_layers.py it is not included in this file.

**Comment by YumengLi007** [comment]
Hi @LongVu219 , thanks for your interests! You could find the load_network_pkl function [here](https://github.com/NVlabs/stylegan3/blob/c233a919a6faee6e36a316ddd4eddababad1adf9/legacy.py#L22). For customized layers, you could find them for instance [here](https://github.com/odegeasslbc/Progressive-GAN-pytorch/blob/master/progan_modules.py).

**Comment by LongVu219** [comment]
@YumengLi007  thank you so much for your help, i have solved that issue.
